# .pre-commit-config.yaml
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.10
  hooks:
    # Linter (修正可能なものは自動修正)
    - id: ruff
      args: [--fix]
    # Formatter
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.0
  hooks:
    - id: mypy
      # 依存関係の型情報を解決するために追加の依存が必要な場合はここに記述
